### ISSUE TITLE
Help! How to build extendsion for dev!

### ISSUE THREAD

**Issue by dungphanxuan** [flarumone/smtp#1]
Hi, do you share me, how to dev extendsion. I want to watch css, js file and buid in realtime, So how can i do it. Like gulp watch ..etc

**Comment by oott123** [comment]
Hi,

Maybe you can refer the official documents.

In a word, you can use `gulp watch` in `js/forum` or `js/admin`.

**Comment by dungphanxuan** [comment]
That great. Thank you.
